package chapter10.project.entity.dinosaur;

public enum DinosaurSpecies {
  TYRANNOSAURUS, TRICERATOPS, VELOCIRAPTOR, STEGOSAURUS,  BRACHIOSAURUS,
  SPINOSAURUS, PARASAUROLOPHUS, ANKYLOSAURUS, PTEROSAUR, PLIOSAURS
}
