package chapter9.project;

public enum EnclosureType {
  RAPTORS_PARK, FLYING_CAGE, POOL_PARK, FREE_PARK, CENTRAL_BUILDING,
  TICKETS_KIOSK, VET_CENTER, FOOD_STORE, PARKING_LOT, SURVEILLANCE_BUILDING
}
